"""Initial migration

Revision ID: 4706762fc489
Revises: 
Create Date: 2025-11-11 01:45:16.658544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4706762fc489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nom_complet', sa.String(length=200), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN_PRINCIPAL', 'CHEF_DEPARTEMENT', 'CHEF_FILIERE', 'ENSEIGNANT', 'ETUDIANT', name='roleutilisateur'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('email_confirme', sa.Boolean(), nullable=True),
    sa.Column('token_confirmation', sa.String(length=255), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token_confirmation')
    )
    op.create_table('enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('matricule_enseignant', sa.String(length=50), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('est_chef_departement', sa.Boolean(), nullable=True),
    sa.Column('est_chef_filiere', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule_enseignant'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lance_par_id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lance_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journaux_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('meta_donnees', sa.JSON(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annees_formation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enseignant_filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('annee_formation_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annee_formation_id'], ['annees_formation.id'], ),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('annee_formation_id', sa.Integer(), nullable=False),
    sa.Column('total_seances', sa.Integer(), nullable=False),
    sa.Column('cm_seances', sa.Integer(), nullable=False),
    sa.Column('td_seances', sa.Integer(), nullable=False),
    sa.Column('tp_seances', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annee_formation_id'], ['annees_formation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affectations_matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seances_cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('annee_formation_id', sa.Integer(), nullable=True),
    sa.Column('type_seance', sa.Enum('CM', 'TD', 'TP', name='typeseance'), nullable=False),
    sa.Column('date_prevue', sa.DateTime(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annee_formation_id'], ['annees_formation.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('statuts_etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('en_rattrapage', sa.Boolean(), nullable=True),
    sa.Column('derniere_evaluation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etudiant_id', 'matiere_id', name='uix_etudiant_matiere_statut')
    )
    op.create_table('presences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seance_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('PRESENT', 'ABSENT', 'EXCUSE', name='statutpresence'), nullable=False),
    sa.Column('date_scan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['seance_id'], ['seances_cours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seance_id', 'etudiant_id', name='uix_seance_etudiant')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presences')
    op.drop_table('statuts_etudiants')
    op.drop_table('seances_cours')
    op.drop_table('affectations_matieres')
    op.drop_table('matieres')
    op.drop_table('etudiants')
    op.drop_table('enseignant_filieres')
    op.drop_table('annees_formation')
    op.drop_table('journaux_actions')
    op.drop_table('importations')
    op.drop_table('filieres')
    op.drop_table('enseignants')
    op.drop_table('utilisateurs')
    op.drop_table('departements')
    # ### end Alembic commands ###
