"""Ajout colonne semestre_id à SeanceCours

Revision ID: 5d629051f8d3
Revises: 7311e65137ad
Create Date: 2025-11-24 14:22:39.753540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d629051f8d3'
down_revision = '7311e65137ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances_cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'semestres', ['semestre_id'], ['id'])

    with op.batch_alter_table('semestres', schema=None) as batch_op:
        batch_op.drop_constraint('semestres_ibfk_2', type_='foreignkey')
        batch_op.drop_column('semestre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semestres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('semestres_ibfk_2', 'semestres', ['semestre_id'], ['id'])

    with op.batch_alter_table('seances_cours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semestre_id')

    # ### end Alembic commands ###
