"""Ajout colonne semestre_id à SeanceCours

Revision ID: 7311e65137ad
Revises: 8a054f6f9871
Create Date: 2025-11-24 14:15:54.386603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7311e65137ad'
down_revision = '8a054f6f9871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semestres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'semestres', ['semestre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semestres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semestre_id')

    # ### end Alembic commands ###
