"""Initial migration

Revision ID: 8a054f6f9871
Revises: d20ef92324e3
Create Date: 2025-11-15 15:15:57.769290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a054f6f9871'
down_revision = 'd20ef92324e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annee_id'], ['annees_formation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('importations', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('matieres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'semestres', ['semestre_id'], ['id'])

    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=mysql.ENUM('PRESENT', 'ABSENT', 'EXCUSE'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=mysql.ENUM('PRESENT', 'ABSENT', 'EXCUSE'),
               nullable=False)

    with op.batch_alter_table('matieres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semestre_id')

    with op.batch_alter_table('importations', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    op.drop_table('semestres')
    # ### end Alembic commands ###
