"""Initial migration

Revision ID: aedfc91a36c6
Revises: 
Create Date: 2025-11-24 17:57:15.982072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aedfc91a36c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affectations_matieres', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('enseignant_filieres', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('seances_cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'semestres', ['semestre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances_cours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semestre_id')

    with op.batch_alter_table('enseignant_filieres', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('affectations_matieres', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
