"""Ajout colonne est_chef_filiere à EnseignantFiliere

Revision ID: d20ef92324e3
Revises: 84954ca712a1
Create Date: 2025-11-13 21:03:27.745981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20ef92324e3'
down_revision = '84954ca712a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant_filieres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('est_chef_filiere', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignant_filieres', schema=None) as batch_op:
        batch_op.drop_column('est_chef_filiere')

    # ### end Alembic commands ###
